name: Boxius - Release

on: [pull_request]
  # push:
  #   tags:
  #     - 'v*'

jobs:
  # build-release:
  #   name: Build Release
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Setup timezone to Asia/Jakarta
  #     run: |
  #       sudo timedatectl set-timezone Asia/Jakarta  
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: ${{ github.ref }}
  #       body: | 

  #       draft: false
  #       prerelease: false        

  deploy-app:   
    # needs: build-release
    name: Deploy App
    runs-on: ubuntu-latest
    env:
      APP_NAME: boxius
      APP_MAIN_PATH: cmd/main/main.go
    steps:
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: "${{ github.token }}"
        target_url: https://assets.rasatmaja.com/
        environment: Staging

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update deployment status (in-progress)
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://assets.rasatmaja.com/
        state: "in_progress"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Building Go Apps
      run: |
          go build -a -ldflags '-extldflags "-static"' -o build/${{ env.APP_NAME }}.app ${{ env.APP_MAIN_PATH }} 

    - name: Deploy app into server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "build/${{ env.APP_NAME }}.app, build/Makefile, build/${{ env.APP_NAME }}.json"
        target: ${{ secrets.SSH_TARGET_PATH }}
        strip_components: 1

    - name: Execute app into server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_TARGET_PATH }}
          make deploy-domainesia

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://assets.rasatmaja.com/
        environment_url: https://assets.rasatmaja.com/
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://assets.rasatmaja.com/
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}            
     